apiVersion: v1
kind: Pod
metadata:
  name: scheduler-pod
  labels:
    app: scheduler
spec:
  containers:
  - name: scheduler-container
    image: giannidylancbhg/scheduler-2
    ports:
    - containerPort: 7681
