apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: opswerks
spec:
  type: NodePort
  selector:
    app: scheduler
  ports:
    - port: 7681
      targetPort: 7681
      nodePort: 30007
